// Comprehensive learning topics for all 120 days (A1, A2, B1, B2)
export const learningTopics = {
  // A1 Level (Days 1-30) - Grundlagen – Überleben im Alltag
  1: { title: "Begrüßung & Verabschiedung", icon: "👋", description: "Greetings and farewells", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  2: { title: "Sich vorstellen", icon: "👤", description: "Introducing yourself", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  3: { title: "Familie & Freunde", icon: "👨‍👩‍👧‍👦", description: "Family and friends", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  4: { title: "Zahlen 0-100", icon: "🔢", description: "Numbers and counting", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  5: { title: "Wochentage & Monate", icon: "📅", description: "Days and months", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  6: { title: "Uhrzeit & Tagesablauf", icon: "⏰", description: "Time and daily routine", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  7: { title: "Nationalitäten & Sprachen", icon: "🌍", description: "Nationalities and languages", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  8: { title: "Stadt & Orientierung", icon: "🏙️", description: "City and orientation", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  9: { title: "Wohnen", icon: "🏠", description: "Living and housing", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  10: { title: "Farben & Formen", icon: "🎨", description: "Colors and shapes", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  11: { title: "Kleidung & Accessoires", icon: "👕", description: "Clothing and accessories", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  12: { title: "Essen & Trinken", icon: "🍽️", description: "Food and drinks", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  13: { title: "Im Café & Restaurant", icon: "☕", description: "Café and restaurant", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  14: { title: "Einkaufen (Lebensmittel)", icon: "🛒", description: "Grocery shopping", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  15: { title: "Einkaufen (Kleidung)", icon: "👗", description: "Clothing shopping", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  16: { title: "Schule & Unterricht", icon: "🎓", description: "School and education", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  17: { title: "Arbeit & Berufe", icon: "💼", description: "Work and professions", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  18: { title: "Freizeit & Hobbys", icon: "🎵", description: "Leisure and hobbies", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  19: { title: "Reisen & Verkehrsmittel", icon: "🚌", description: "Travel and transport", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  20: { title: "Am Flughafen & Bahnhof", icon: "✈️", description: "Airport and train station", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  21: { title: "Wetter & Jahreszeiten", icon: "🌤️", description: "Weather and seasons", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  22: { title: "Gesundheit & Körperteile", icon: "🏥", description: "Health and body parts", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  23: { title: "Beim Arzt", icon: "🩺", description: "At the doctor", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  24: { title: "Tiere", icon: "🐕", description: "Animals", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  25: { title: "Natur", icon: "🌱", description: "Nature", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  26: { title: "Feiertage & Geburtstage", icon: "🎉", description: "Holidays and birthdays", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  27: { title: "Alltägliche Gegenstände", icon: "📱", description: "Everyday objects", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  28: { title: "Häufige Adjektive", icon: "📝", description: "Common adjectives", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  29: { title: "Häufige Verben", icon: "🏃", description: "Common verbs", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  30: { title: "Wiederholung A1", icon: "🔄", description: "A1 Review", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  
  // A2 Level (Days 31-60) - Alltagswelt erweitern
  31: { title: "Wiederholung A1", icon: "🔄", description: "A1 Review - Fill important gaps", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  32: { title: "Familie im Detail", icon: "👨‍👩‍👧‍👦", description: "Family relationships and kinship", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  33: { title: "Wohnen & Nachbarschaft", icon: "🏘️", description: "Living and neighborhood", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  34: { title: "Stadt & Orientierung", icon: "🗺️", description: "City navigation and directions", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  35: { title: "Einkaufen im Supermarkt", icon: "🛍️", description: "Supermarket products and packaging", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  36: { title: "Kleidung (Stoffe & Größen)", icon: "👔", description: "Clothing materials, sizes and stores", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  37: { title: "Essen (Rezepte & Zubereitung)", icon: "👨‍🍳", description: "Recipes, cooking and restaurants", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  38: { title: "Freizeit & Hobbys im Detail", icon: "🎨", description: "Detailed leisure and hobbies", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  39: { title: "Medien", icon: "📺", description: "TV, radio and newspapers", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  40: { title: "Internet & soziale Medien", icon: "💻", description: "Internet and social media", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  41: { title: "Reisen & Urlaub", icon: "🏖️", description: "Travel, hotels and sightseeing", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  42: { title: "Verkehrsmittel (Fahrplan & Tickets)", icon: "🎫", description: "Transport schedules and tickets", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  43: { title: "Wetter (Prognose & Klima)", icon: "🌦️", description: "Weather forecast and climate", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  44: { title: "Arztbesuch (Krankheiten & Apotheke)", icon: "💊", description: "Illnesses and pharmacy", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  45: { title: "Gesundheit (Sport & Fitness)", icon: "🏃‍♀️", description: "Sports, fitness and nutrition", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  46: { title: "Arbeit & Büroalltag", icon: "💼", description: "Work and office routine", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  47: { title: "Schule & Studium", icon: "🎓", description: "School subjects and exams", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  48: { title: "Tagesablauf (detailliert)", icon: "⏰", description: "Detailed daily routine", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  49: { title: "Umwelt (Stadt vs. Natur)", icon: "🌱", description: "Environment: city vs nature", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  50: { title: "Dienstleistungen", icon: "🏪", description: "Services: post, bank, hairdresser", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  51: { title: "Kultur", icon: "🎭", description: "Cinema, theater and museum", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  52: { title: "Musik & Kunst", icon: "🎵", description: "Music and art", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  53: { title: "Feiertage & Traditionen", icon: "🎉", description: "Holidays and traditions", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  54: { title: "Gefühle & Charaktereigenschaften", icon: "😊", description: "Feelings and character traits", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  55: { title: "Einladungen & Termine", icon: "📅", description: "Invitations and appointments", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  56: { title: "Telefongespräche", icon: "📞", description: "Phone conversations", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  57: { title: "Briefe & E-Mails", icon: "✉️", description: "Letters and emails", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  58: { title: "Häufige Redewendungen", icon: "💬", description: "Common expressions in daily life", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  59: { title: "Smalltalk-Themen", icon: "🗣️", description: "Small talk topics", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  60: { title: "Wiederholung A2", icon: "🔄", description: "A2 Review", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  
  // B1 Level (Days 61-90) - Selbstständige Sprachverwendung
  61: { title: "Wiederholung A2", icon: "🔄", description: "A2 Review", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  62: { title: "Familie & Beziehungen", icon: "👨‍👩‍👧‍👦", description: "Family and relationships in social context", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  63: { title: "Ausbildung & Karriere", icon: "🎓", description: "Education and career", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  64: { title: "Arbeitswelt (Bewerbung)", icon: "📝", description: "Work world: applications and interviews", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  65: { title: "Schule & Bildungssystem", icon: "🏫", description: "School and education system", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  66: { title: "Reisen im Ausland", icon: "🌍", description: "Traveling abroad: problems and solutions", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  67: { title: "Politik & Gesellschaft", icon: "🏛️", description: "Politics and society: basic concepts", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  68: { title: "Medien (Nachrichten)", icon: "📰", description: "Media: news and fake news", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  69: { title: "Umwelt & Nachhaltigkeit", icon: "🌱", description: "Environment and sustainability: basics", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  70: { title: "Technologie", icon: "📱", description: "Technology: phone, computer, internet", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  71: { title: "Gesundheit & Medizin", icon: "🏥", description: "Health and medicine: everyday and technical terms", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  72: { title: "Ernährung & Lifestyle", icon: "🥗", description: "Nutrition and lifestyle", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  73: { title: "Sport & Freizeit", icon: "⚽", description: "Sports and leisure: social significance", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  74: { title: "Kunst & Kultur", icon: "🎨", description: "Art and culture: music and literature", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  75: { title: "Traditionen & Bräuche", icon: "🎭", description: "Traditions and customs in Russia/Germany", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  76: { title: "Wissenschaft", icon: "🔬", description: "Science: general knowledge", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  77: { title: "Geschichte", icon: "📚", description: "History: important events", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  78: { title: "Natur & Klima", icon: "🌍", description: "Nature and climate: global problems", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  79: { title: "Verkehr & Mobilität", icon: "🚗", description: "Transport and mobility", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  80: { title: "Wohnen & Lebensformen", icon: "🏘️", description: "Living and life forms: city, country, shared living", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  81: { title: "Gefühle & Psychologie", icon: "🧠", description: "Feelings and psychology: detailed", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  82: { title: "Freundschaft & Partnerschaft", icon: "💕", description: "Friendship and partnership", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  83: { title: "Konsum & Werbung", icon: "🛍️", description: "Consumption and advertising", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  84: { title: "Geld & Finanzen", icon: "💰", description: "Money and finances", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  85: { title: "Gesellschaftliche Werte", icon: "⚖️", description: "Social values: freedom, equality", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  86: { title: "Diskussion führen", icon: "🗣️", description: "Leading discussions: pro and contra", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  87: { title: "Argumente begründen", icon: "💭", description: "Justifying arguments and giving examples", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  88: { title: "Zukunft", icon: "🔮", description: "Future: plans and dreams", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  89: { title: "Probleme & Lösungen", icon: "🔧", description: "Problems and solutions in daily life", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  90: { title: "Wiederholung B1", icon: "🔄", description: "B1 Review", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  
  // B2 Level (Days 91-120) - Fortgeschrittene Kommunikation
  91: { title: "Wiederholung B1", icon: "🔄", description: "B1 Review", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  92: { title: "Politik im Detail", icon: "🏛️", description: "Politics in detail: democracy and government", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  93: { title: "Gesellschaftliche Probleme", icon: "⚠️", description: "Social problems: migration and integration", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  94: { title: "Wirtschaft", icon: "💼", description: "Economy: market, trade, globalization", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  95: { title: "Geld & Banken", icon: "🏦", description: "Money and banks: debt and investments", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  96: { title: "Wissenschaft & Forschung", icon: "🔬", description: "Science and research: technology and medicine", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  97: { title: "Umweltprobleme", icon: "🌍", description: "Environmental problems: climate change and sustainability", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  98: { title: "Energie", icon: "⚡", description: "Energy: nuclear and renewable energy", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  99: { title: "Medienkritik", icon: "📺", description: "Media criticism: manipulation and social media", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  100: { title: "Kunst & Kultur (klassisch)", icon: "🎭", description: "Art and culture: classical and modern", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  101: { title: "Literatur", icon: "📚", description: "Literature: authors and genres", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  102: { title: "Film & Theater", icon: "🎬", description: "Film and theater: analysis", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  103: { title: "Musik", icon: "🎵", description: "Music: styles and social role", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  104: { title: "Geschichte (politisch)", icon: "📜", description: "History: political events and wars", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  105: { title: "Philosophie & Ethik", icon: "🤔", description: "Philosophy and ethics", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  106: { title: "Religion & Weltanschauungen", icon: "⛪", description: "Religion and worldviews", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
  107: { title: "Gesundheit im Detail", icon: "🏥", description: "Health in detail: psychology and prevention", highlights: [], gradientColors: ['#89f7fe', '#66a6ff'] },
  108: { title: "Globalisierung", icon: "🌐", description: "Globalization and internationalization", highlights: [], gradientColors: ['#fdbb2d', '#22c1c3'] },
  109: { title: "Arbeit im 21. Jahrhundert", icon: "💻", description: "Work in the 21st century: remote work and AI", highlights: [], gradientColors: ['#ee9ca7', '#ffdde1'] },
  110: { title: "Bildung & Forschungssysteme", icon: "🎓", description: "Education and research systems: comparison", highlights: [], gradientColors: ['#83a4d4', '#b6fbff'] },
  111: { title: "Technologie & Zukunftsvisionen", icon: "🚀", description: "Technology and future visions", highlights: [], gradientColors: ['#cd9cf2', '#f6f3ff'] },
  112: { title: "Politik & Umwelt", icon: "🌍", description: "Politics and environment: conferences and agreements", highlights: [], gradientColors: ['#ffeaa7', '#fab1a0'] },
  113: { title: "Interkulturelle Kommunikation", icon: "🤝", description: "Intercultural communication", highlights: [], gradientColors: ['#667eea', '#764ba2'] },
  114: { title: "Digitalisierung: Chancen & Risiken", icon: "💻", description: "Digitalization: opportunities and risks", highlights: [], gradientColors: ['#f093fb', '#f5576c'] },
  115: { title: "Argumentationstechniken", icon: "💭", description: "Argumentation techniques: agreeing and disagreeing", highlights: [], gradientColors: ['#4facfe', '#00f2fe'] },
  116: { title: "Redewendungen für Debatten", icon: "🗣️", description: "Expressions for debates", highlights: [], gradientColors: ['#fa709a', '#fee140'] },
  117: { title: "Schriftliche Texte", icon: "✍️", description: "Written texts: essays and comments", highlights: [], gradientColors: ['#a8edea', '#fed6e3'] },
  118: { title: "Mündliche Prüfung", icon: "🎤", description: "Oral exam: expressing opinions", highlights: [], gradientColors: ['#ff9a9e', '#fecfef'] },
  119: { title: "Diskussion & Rollenspiele", icon: "🎭", description: "Discussion and role plays: simulation", highlights: [], gradientColors: ['#a18cd1', '#fbc2eb'] },
  120: { title: "Wiederholung B2", icon: "🔄", description: "B2 Review: summarize all topics", highlights: [], gradientColors: ['#ffecd2', '#fcb69f'] },
};