import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  de: {
    welcome: 'Willkommen zurück bei BiLi!',
    chooseDirection: 'Wähle deine Sprachrichtung',
    selectLevel: 'Wähle dein angestrebtes Niveau',
    profile: 'Profil',
    profileSoon: 'Profil (bald verfügbar)',
    germanToRussian: 'Deutsch → Russisch',
    russianToGerman: 'Russisch → Deutsch',
    motherTongueTitle: 'Was ist deine Muttersprache?',
    german: 'Deutsch',
    russian: 'Russisch',
    learningDirection: 'Lernrichtung',
    motherTongue: 'Muttersprache',
    changeMotherTongue: 'Muttersprache ändern',
    changeDirection: 'Richtung ändern',
    editProfile: 'Profil bearbeiten',
    logout: 'Abmelden',
    day1VocabTitle: 'Tag 1 – Vokabeln',
    wordList: 'Wortliste',
    example: 'Beispiel',
    continue: 'Weiter',
    comingSoon: 'Demnächst verfügbar',
    day: 'Tag',
    vocabulary: 'Vokabeln',
    speaking: 'Sprechen',
    minutes: 'Min',
    wordsTitle: 'Wörter & Beispiele',
    flashcardsTitle: 'Karteikarten',
    startPractice: 'Üben starten',
    showAnswer: 'Antwort anzeigen',
    hideAnswer: 'Antwort verbergen',
    next: 'Weiter',
    previous: 'Zurück',
    iKnewThis: 'Ich wusste es',
    iNeedPractice: 'Ich brauche Übung',
    // Auth translations
    welcomeTagline: 'Deine Sprach-Lern-Reise beginnt hier',
    welcomeTitle: 'Willkommen bei BiLi',
    welcomeSubtitle: 'Lerne Deutsch und Russisch',
    createAccount: 'Konto erstellen',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    email: 'E-Mail',
    password: 'Passwort',
    username: 'Benutzername',
    confirmPassword: 'Passwort bestätigen',
    forgotPassword: 'Passwort vergessen?',
    resetPassword: 'Passwort zurücksetzen',
    emailPlaceholder: 'deine@email.de',
    passwordPlaceholder: 'Gib dein Passwort ein',
    usernamePlaceholder: 'Wähle einen Benutzernamen',
    confirmPasswordPlaceholder: 'Passwort bestätigen',
    dontHaveAccount: 'Noch kein Konto?',
    alreadyHaveAccount: 'Bereits ein Konto?',
    continueAgreement: 'Durch Fortfahren stimmst du unseren Nutzungsbedingungen zu',
    signInError: 'Anmeldung fehlgeschlagen',
    signInErrorGeneric: 'Es gab ein Problem bei der Anmeldung. Bitte versuche es erneut.',
    signUpError: 'Registrierung fehlgeschlagen',
    signUpErrorGeneric: 'Es gab ein Problem bei der Registrierung. Bitte versuche es erneut.',
    resetPasswordError: 'Passwort-Reset fehlgeschlagen',
    resetPasswordErrorGeneric: 'Es gab ein Problem beim Zurücksetzen des Passworts.',
    checkEmail: 'E-Mail prüfen',
    checkEmailMessage: 'Wir haben dir eine Bestätigungs-E-Mail gesendet. Bitte prüfe dein Postfach.',
    resetPasswordEmailSent: 'Wir haben dir einen Link zum Zurücksetzen des Passworts gesendet.',
    resetPasswordSubtitle: 'Passwort vergessen?',
    resetPasswordDescription: 'Gib deine E-Mail-Adresse ein und wir senden dir einen Link zum Zurücksetzen deines Passworts.',
    sendResetEmail: 'Reset-Link senden',
    rememberPassword: 'Passwort wieder eingefallen?',
    signingIn: 'Anmeldung läuft...',
    creatingAccount: 'Konto wird erstellt...',
    sendingEmail: 'E-Mail wird gesendet...',
    ok: 'OK',
    confirmLogout: 'Abmelden bestätigen',
    confirmLogoutMessage: 'Bist du sicher, dass du dich abmelden möchtest?',
    cancel: 'Abbrechen',
    logoutError: 'Abmeldung fehlgeschlagen',
    updateError: 'Update fehlgeschlagen',
    updateSuccess: 'Erfolgreich aktualisiert',
    profileUpdated: 'Profil wurde erfolgreich aktualisiert',
    updateErrorGeneric: 'Es gab ein Problem beim Aktualisieren des Profils',
    syncSettings: 'Einstellungen synchronisieren',
    updating: 'Aktualisierung läuft...',
    learningLevel: 'Lernstufe',
    // Flashcard rating translations
    rateYourKnowledge: 'Wie gut kennst du dieses Wort?',
    perfect: 'Perfekt',
    good: 'Gut',
    ok: 'OK',
    difficult: 'Schwierig',
    needHelp: 'Hilfe',
    practiceAgain: 'Nochmal üben',
    wordsLearned: 'Wörter gelernt',
    totalWords: 'Gesamt',
    error: 'Fehler',
    errorSavingProgress: 'Fehler beim Speichern des Fortschritts',
    congratulations: 'Glückwunsch!',
    completedAllCards: 'Du hast alle Karten dieser Lektion bearbeitet!',
    loading: 'Wird geladen',
    noWordsYet: 'Noch keine Wörter',
    noWordsToPreview: 'Keine Wörter zu üben',
    practiceOtherCategories: 'Versuche andere Kategorien zu üben',
    practiceComplete: 'Übung abgeschlossen!',
    practiceCompleteMessage: 'Du hast alle Wörter in dieser Kategorie geübt.',
    practiceMode: 'Übungsmodus',
    tapToFlip: 'Zum Umdrehen tippen',
    howWellKnow: 'Wie gut kennst du dieses Wort?',
    allWordsReviewed: 'Du hast alle Wörter in dieser Kategorie überprüft.',
    noWordsToReview: 'Keine Wörter zu überprüfen',
    allWordsCompleted: 'Alle Wörter in dieser Kategorie wurden abgeschlossen!',
    backToGallery: 'Zurück zur Galerie',
    wordMoved: 'Wort verschoben!',
    movedTo: 'verschoben zu',
    updating: 'Aktualisiere...',
    saveError: 'Fehler beim Speichern des Fortschritts',
    // Home screen translations
    todaysAdventure: 'Das heutige Lernabenteuer wartet auf dich!',
    learningProgress: 'Lernfortschritt',
    days: 'Tage',
    comingUp: 'Als Nächstes',
    tapToReveal: '👆 Tippen zum Aufdecken',
    readyToLearn: 'Bereit für das heutige Lernabenteuer?',
    startLearning: '🚀 Lernen starten',
    // Gallery translations
    gallery: 'Wort-Galerie',
    yourProgress: 'Ihre Lernreise',
    keepGoing: 'Weiter so!',
    masteryLevels: 'Beherrschungsstufen',
    words: 'Wörter',
    // Practice Mode translations
    practiceMode: 'Übungsmodus',
    error: 'Fehler',
    saveError: 'Speichern fehlgeschlagen',
    practiceComplete: 'Übung abgeschlossen!',
    allWordsReviewed: 'Sie haben alle Wörter in dieser Kategorie überprüft.',
    ok: 'OK',
    wordMoved: 'Wort verschoben!',
    movedTo: 'verschoben zu',
    loading: 'Lädt...',
    noWordsToReview: 'Keine Wörter zu überprüfen',
    allWordsCompleted: 'Alle Wörter in dieser Kategorie wurden abgeschlossen!',
    backToGallery: 'Zurück zur Galerie',
    tapToFlip: 'Zum Umdrehen tippen',
    howWellKnow: 'Wie gut kennst du dieses Wort?',
    updating: 'Aktualisiere...',
    // Profile screen translations
    learning: 'Lernen',
    masteryLevel: 'Beherrschungsgrad',
    quickStats: 'Schnelle Statistiken',
    currentStreak: 'Aktuelle Serie',
    totalWords: 'Gesamte Wörter',
    learned: 'gelernt',
    practiceSessions: 'Übungssitzungen',
    completed: 'abgeschlossen',
    dailyAverage: 'Tagesdurchschnitt',
    sessions: 'Sitzungen',
    masteryBreakdown: 'Beherrschungsaufschlüsselung',
    syncSettings: 'Einstellungen synchronisieren',
    confirmLogout: 'Abmeldung bestätigen',
    confirmLogoutMessage: 'Möchten Sie sich wirklich abmelden?',
    cancel: 'Abbrechen',
    logoutError: 'Abmeldefehler',
    updateError: 'Aktualisierungsfehler',
    updateSuccess: 'Erfolgreich aktualisiert',
    profileUpdated: 'Profil wurde aktualisiert',
    updateErrorGeneric: 'Beim Aktualisieren ist ein Fehler aufgetreten',
    continueAgreement: 'Durch Fortfahren stimmst du unseren Nutzungsbedingungen zu',
    alreadyHaveAccount: 'Schon ein Konto?',
    signInNow: 'Jetzt anmelden!',
    interactiveLearning: 'Interaktives Lernen',
    trackProgress: 'Fortschritt verfolgen',
    // Learning topic titles
    topics: {
      'Small Talk & Basics': 'Small Talk & Grundlagen',
      'Family & Relationships': 'Familie & Beziehungen',
      'Home & Living': 'Zuhause & Wohnen',
      'Food & Dining': 'Essen & Restaurant',
      'Work & Education': 'Arbeit & Bildung',
      'Shopping & Money': 'Einkaufen & Geld',
      'Transportation & Travel': 'Transport & Reisen',
      'Health & Body': 'Gesundheit & Körper',
      'Time & Weather': 'Zeit & Wetter',
      'Hobbies & Entertainment': 'Hobbys & Unterhaltung',
      'Technology & Communication': 'Technologie & Kommunikation',
      'Nature & Environment': 'Natur & Umwelt',
      'Culture & Traditions': 'Kultur & Traditionen',
      'Advanced Conversations': 'Fortgeschrittene Gespräche'
    },
    topicDescriptions: {
      'Greetings, introductions & courtesy': 'Begrüßungen, Vorstellungen & Höflichkeit',
      'People in your life': 'Menschen in Ihrem Leben',
      'Your personal space': 'Ihr persönlicher Raum',
      'Meals and culinary culture': 'Mahlzeiten und kulinarische Kultur',
      'Professional and academic life': 'Berufliches und akademisches Leben',
      'Commerce and transactions': 'Handel und Transaktionen',
      'Getting around and exploring': 'Fortbewegung und Erkundung',
      'Wellness and medical topics': 'Wellness und medizinische Themen',
      'Temporal and meteorological expressions': 'Zeitliche und meteorologische Ausdrücke',
      'Leisure activities and fun': 'Freizeitaktivitäten und Spaß',
      'Digital life and connectivity': 'Digitales Leben und Konnektivität',
      'The natural world around us': 'Die natürliche Welt um uns herum',
      'Cultural understanding and customs': 'Kulturelles Verständnis und Bräuche',
      'Complex topics and discussions': 'Komplexe Themen und Diskussionen'
    },
    topicHighlights: {
      'Hello & goodbye': 'Hallo & Auf Wiedersehen',
      'Please & thank you': 'Bitte & Danke',
      'Basic questions': 'Grundlegende Fragen',
      'Family members': 'Familienmitglieder',
      'Relationships': 'Beziehungen',
      'Personal connections': 'Persönliche Verbindungen',
      'Rooms & furniture': 'Zimmer & Möbel',
      'Daily routines': 'Tägliche Routinen',
      'Household items': 'Haushaltsgegenstände',
      'Restaurants & ordering': 'Restaurants & Bestellen',
      'Cooking terms': 'Kochbegriffe',
      'Food preferences': 'Essensvorlieben',
      'Office vocabulary': 'Büro-Vokabular',
      'School terms': 'Schulbegriffe',
      'Career conversations': 'Karrieregespräche',
      'Shopping phrases': 'Einkaufsphrasen',
      'Prices & payment': 'Preise & Bezahlung',
      'Stores & services': 'Geschäfte & Dienstleistungen',
      'Public transport': 'Öffentliche Verkehrsmittel',
      'Directions': 'Wegbeschreibungen',
      'Travel planning': 'Reiseplanung',
      'Body parts': 'Körperteile',
      'Symptoms': 'Symptome',
      'Doctor visits': 'Arztbesuche',
      'Days & seasons': 'Tage & Jahreszeiten',
      'Weather conditions': 'Wetterbedingungen',
      'Time expressions': 'Zeitausdrücke',
      'Sports & games': 'Sport & Spiele',
      'Music & movies': 'Musik & Filme',
      'Weekend activities': 'Wochenendaktivitäten',
      'Phone & internet': 'Telefon & Internet',
      'Social media': 'Soziale Medien',
      'Tech problems': 'Technische Probleme',
      'Animals & plants': 'Tiere & Pflanzen',
      'Geography': 'Geographie',
      'Environmental topics': 'Umweltthemen',
      'Holidays & festivals': 'Feiertage & Festivals',
      'Traditions': 'Traditionen',
      'Cultural expressions': 'Kulturelle Ausdrücke',
      'Opinions & debates': 'Meinungen & Debatten',
      'Abstract concepts': 'Abstrakte Konzepte',
      'Fluent expression': 'Fließende Ausdrucksweise'
    },
  },
  ru: {
    welcome: 'С возвращением в BiLi!',
    chooseDirection: 'Выберите направление языка',
    selectLevel: 'Выберите желаемый уровень',
    profile: 'Профиль',
    profileSoon: 'Профиль (скоро)',
    germanToRussian: 'Немецкий → Русский',
    russianToGerman: 'Русский → Немецкий',
    motherTongueTitle: 'Какой у вас родной язык?',
    german: 'Немецкий',
    russian: 'Русский',
    learningDirection: 'Направление обучения',
    motherTongue: 'Родной язык',
    changeMotherTongue: 'Изменить родной язык',
    changeDirection: 'Изменить направление',
    editProfile: 'Редактировать профиль',
    logout: 'Выйти',
    day1VocabTitle: 'День 1 – Словарь',
    wordList: 'Список слов',
    example: 'Пример',
    continue: 'Далее',
    comingSoon: 'Скоро',
    day: 'День',
    vocabulary: 'Словарь',
    speaking: 'Разговор',
    minutes: 'мин',
    wordsTitle: 'Слова и примеры',
    flashcardsTitle: 'Флеш-карты',
    startPractice: 'Начать практику',
    showAnswer: 'Показать ответ',
    hideAnswer: 'Скрыть ответ',
    next: 'Далее',
    previous: 'Назад',
    iKnewThis: 'Я знал это',
    iNeedPractice: 'Нужно потренироваться',
    // Auth translations
    welcomeTagline: 'Ваше языковое путешествие начинается здесь',
    welcomeTitle: 'Добро пожаловать в BiLi',
    welcomeSubtitle: 'Изучайте немецкий и русский с помощью современных интерактивных методов',
    createAccount: 'Создать аккаунт',
    signIn: 'Войти',
    signUp: 'Регистрация',
    email: 'Электронная почта',
    password: 'Пароль',
    username: 'Имя пользователя',
    confirmPassword: 'Подтвердить пароль',
    forgotPassword: 'Забыли пароль?',
    resetPassword: 'Сбросить пароль',
    emailPlaceholder: 'ваша@почта.ru',
    passwordPlaceholder: 'Введите пароль',
    usernamePlaceholder: 'Выберите имя пользователя',
    confirmPasswordPlaceholder: 'Подтвердите пароль',
    dontHaveAccount: 'Нет аккаунта?',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    continueAgreement: 'Продолжая, вы соглашаетесь с нашими условиями использования',
    signInError: 'Ошибка входа',
    signInErrorGeneric: 'Возникла проблема при входе. Пожалуйста, попробуйте снова.',
    signUpError: 'Ошибка регистрации',
    signUpErrorGeneric: 'Возникла проблема при регистрации. Пожалуйста, попробуйте снова.',
    resetPasswordError: 'Ошибка сброса пароля',
    resetPasswordErrorGeneric: 'Возникла проблема при сбросе пароля.',
    checkEmail: 'Проверьте почту',
    checkEmailMessage: 'Мы отправили вам письмо с подтверждением. Проверьте свой почтовый ящик.',
    resetPasswordEmailSent: 'Мы отправили вам ссылку для сброса пароля.',
    resetPasswordSubtitle: 'Забыли пароль?',
    resetPasswordDescription: 'Введите ваш адрес электронной почты, и мы отправим вам ссылку для сброса пароля.',
    sendResetEmail: 'Отправить ссылку',
    rememberPassword: 'Вспомнили пароль?',
    signingIn: 'Вход в систему...',
    creatingAccount: 'Создание аккаунта...',
    sendingEmail: 'Отправка письма...',
    ok: 'ОК',
    confirmLogout: 'Подтвердить выход',
    confirmLogoutMessage: 'Вы уверены, что хотите выйти?',
    cancel: 'Отмена',
    logoutError: 'Ошибка выхода',
    updateError: 'Ошибка обновления',
    updateSuccess: 'Успешно обновлено',
    profileUpdated: 'Профиль успешно обновлен',
    updateErrorGeneric: 'Возникла проблема при обновлении профиля',
    syncSettings: 'Синхронизировать настройки',
    updating: 'Обновление...',
    learningLevel: 'Уровень изучения',
    // Flashcard rating translations
    rateYourKnowledge: 'Насколько хорошо вы знаете это слово?',
    perfect: 'Отлично',
    good: 'Хорошо',
    ok: 'Нормально',
    difficult: 'Сложно',
    needHelp: 'Нужна помощь',
    practiceAgain: 'Повторить',
    wordsLearned: 'Слов изучено',
    totalWords: 'Всего',
    error: 'Ошибка',
    errorSavingProgress: 'Ошибка при сохранении прогресса',
    congratulations: 'Поздравляем!',
    completedAllCards: 'Вы завершили все карточки этого урока!',
    loading: 'Загрузка',
    noWordsYet: 'Пока нет слов',
    noWordsToPreview: 'Нет слов для практики',
    practiceOtherCategories: 'Попробуйте другие категории',
    practiceComplete: 'Практика завершена!',
    practiceCompleteMessage: 'Вы повторили все слова в этой категории.',
    practiceMode: 'Режим практики',
    tapToFlip: 'Нажмите, чтобы перевернуть',
    howWellKnow: 'Насколько хорошо вы знаете это слово?',
    allWordsReviewed: 'Вы просмотрели все слова в этой категории.',
    noWordsToReview: 'Нет слов для просмотра',
    allWordsCompleted: 'Все слова в этой категории завершены!',
    backToGallery: 'Назад в галерею',
    wordMoved: 'Слово перемещено!',
    movedTo: 'перемещено в',
    updating: 'Обновление...',
    saveError: 'Ошибка сохранения прогресса',
    // Home screen translations
    todaysAdventure: 'Сегодняшнее приключение в изучении ждет вас!',
    learningProgress: 'Прогресс обучения',
    days: 'дней',
    comingUp: 'Далее',
    tapToReveal: '👆 Нажмите, чтобы открыть',
    readyToLearn: 'Готовы к сегодняшнему приключению в изучении?',
    startLearning: '🚀 Начать изучение',
    // Gallery translations
    gallery: 'Галерея слов',
    yourProgress: 'Ваш путь в изучении',
    keepGoing: 'Продолжайте!',
    masteryLevels: 'Уровни владения',
    words: 'слов',
    // Practice Mode translations
    practiceMode: 'Режим практики',
    error: 'Ошибка',
    saveError: 'Ошибка сохранения',
    practiceComplete: 'Практика завершена!',
    allWordsReviewed: 'Вы просмотрели все слова в этой категории.',
    ok: 'ОК',
    wordMoved: 'Слово перемещено!',
    movedTo: 'перемещено в',
    loading: 'Загружается...',
    noWordsToReview: 'Нет слов для просмотра',
    allWordsCompleted: 'Все слова в этой категории завершены!',
    backToGallery: 'Назад в галерею',
    tapToFlip: 'Нажмите, чтобы перевернуть',
    howWellKnow: 'Насколько хорошо вы знаете это слово?',
    updating: 'Обновляется...',
    // Profile screen translations
    learning: 'Изучение',
    masteryLevel: 'Уровень владения',
    quickStats: 'Быстрая статистика',
    currentStreak: 'Текущая серия',
    totalWords: 'Всего слов',
    learned: 'изучено',
    practiceSessions: 'Сессии практики',
    completed: 'завершено',
    dailyAverage: 'Дневное среднее',
    sessions: 'сессий',
    masteryBreakdown: 'Разбивка по владению',
    syncSettings: 'Синхронизировать настройки',
    confirmLogout: 'Подтвердить выход',
    confirmLogoutMessage: 'Вы действительно хотите выйти?',
    cancel: 'Отмена',
    logoutError: 'Ошибка выхода',
    updateError: 'Ошибка обновления',
    updateSuccess: 'Успешно обновлено',
    profileUpdated: 'Профиль обновлен',
    updateErrorGeneric: 'Произошла ошибка при обновлении',
    continueAgreement: 'Продолжая, вы соглашаетесь с нашими условиями использования',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    signInNow: 'Войти сейчас!',
    interactiveLearning: 'Интерактивное обучение',
    trackProgress: 'Отслеживайте прогресс',
    // Learning topic titles
    topics: {
      'Small Talk & Basics': 'Светская беседа и основы',
      'Family & Relationships': 'Семья и отношения',
      'Home & Living': 'Дом и быт',
      'Food & Dining': 'Еда и рестораны',
      'Work & Education': 'Работа и образование',
      'Shopping & Money': 'Покупки и деньги',
      'Transportation & Travel': 'Транспорт и путешествия',
      'Health & Body': 'Здоровье и тело',
      'Time & Weather': 'Время и погода',
      'Hobbies & Entertainment': 'Хобби и развлечения',
      'Technology & Communication': 'Технологии и общение',
      'Nature & Environment': 'Природа и окружающая среда',
      'Culture & Traditions': 'Культура и традиции',
      'Advanced Conversations': 'Продвинутые разговоры'
    },
    topicDescriptions: {
      'Greetings, introductions & courtesy': 'Приветствия, знакомства и вежливость',
      'People in your life': 'Люди в вашей жизни',
      'Your personal space': 'Ваше личное пространство',
      'Meals and culinary culture': 'Еда и кулинарная культура',
      'Professional and academic life': 'Профессиональная и академическая жизнь',
      'Commerce and transactions': 'Торговля и транзакции',
      'Getting around and exploring': 'Передвижение и исследование',
      'Wellness and medical topics': 'Здоровье и медицинские темы',
      'Temporal and meteorological expressions': 'Временные и метеорологические выражения',
      'Leisure activities and fun': 'Досуг и развлечения',
      'Digital life and connectivity': 'Цифровая жизнь и связь',
      'The natural world around us': 'Природный мир вокруг нас',
      'Cultural understanding and customs': 'Культурное понимание и обычаи',
      'Complex topics and discussions': 'Сложные темы и дискуссии'
    },
    topicHighlights: {
      'Hello & goodbye': 'Привет и до свидания',
      'Please & thank you': 'Пожалуйста и спасибо',
      'Basic questions': 'Основные вопросы',
      'Family members': 'Члены семьи',
      'Relationships': 'Отношения',
      'Personal connections': 'Личные связи',
      'Rooms & furniture': 'Комнаты и мебель',
      'Daily routines': 'Ежедневные рутины',
      'Household items': 'Предметы домашнего обихода',
      'Restaurants & ordering': 'Рестораны и заказы',
      'Cooking terms': 'Кулинарные термины',
      'Food preferences': 'Пищевые предпочтения',
      'Office vocabulary': 'Офисная лексика',
      'School terms': 'Школьные термины',
      'Career conversations': 'Разговоры о карьере',
      'Shopping phrases': 'Фразы для покупок',
      'Prices & payment': 'Цены и оплата',
      'Stores & services': 'Магазины и услуги',
      'Public transport': 'Общественный транспорт',
      'Directions': 'Направления',
      'Travel planning': 'Планирование поездок',
      'Body parts': 'Части тела',
      'Symptoms': 'Симптомы',
      'Doctor visits': 'Визиты к врачу',
      'Days & seasons': 'Дни и времена года',
      'Weather conditions': 'Погодные условия',
      'Time expressions': 'Временные выражения',
      'Sports & games': 'Спорт и игры',
      'Music & movies': 'Музыка и фильмы',
      'Weekend activities': 'Выходные мероприятия',
      'Phone & internet': 'Телефон и интернет',
      'Social media': 'Социальные сети',
      'Tech problems': 'Технические проблемы',
      'Animals & plants': 'Животные и растения',
      'Geography': 'География',
      'Environmental topics': 'Экологические темы',
      'Holidays & festivals': 'Праздники и фестивали',
      'Traditions': 'Традиции',
      'Cultural expressions': 'Культурные выражения',
      'Opinions & debates': 'Мнения и дебаты',
      'Abstract concepts': 'Абстрактные понятия',
      'Fluent expression': 'Беглое выражение'
    },
  },
};

const AppLanguageContext = createContext({
  language: 'de',
  setLanguage: () => {},
  direction: 'de-ru',
  setDirection: () => {},
  level: 'A1',
  setLevel: () => {},
  t: (key) => key,
});

export function AppLanguageProvider({ children }) {
  const [language, setLanguage] = useState('de');
  const [direction, setDirection] = useState('de-ru');
  const [level, setLevel] = useState('A1');

  const value = useMemo(() => ({
    language,
    setLanguage,
    direction,
    setDirection,
    level,
    setLevel,
    t: (key) => translations[language]?.[key] ?? key,
  }), [language, direction, level]);

  return (
    <AppLanguageContext.Provider value={value}>{children}</AppLanguageContext.Provider>
  );
}

export function useAppLanguage() {
  return useContext(AppLanguageContext);
}


